string model_file
string substrate_file
bool generate_grasps
bool generate_jigs
float64 collision_volume_threshold
---
bool success
AssemblyStep[] steps
---
# Feedback message strucure goes here
float32 progress